### ISSUE TITLE
wallpanel actually freezes/crashes on my 2 tablets since a recent update whenever wifi connection is lost. I can easily reproduce it, unplug or reboot my router, and usually both tablets will, after a minute or so,  show android's "app not responding" and they dont recover.  They are very different tablets (one is android 9 I think, the other 10).

### ISSUE THREAD

**Issue by thanksmister** [thanksmister/wallpanel-android#265]
wallpanel actually freezes/crashes on my 2 tablets since a recent update whenever wifi connection is lost. I can easily reproduce it, unplug or reboot my router, and usually both tablets will, after a minute or so,  show android's "app not responding" and they dont recover.  They are very different tablets (one is android 9 I think, the other 10). 
It started happening when I upgraded a week or so ago to the latest version which supports having wallpanel act as a home screen. Enabling or disabling that doesnt seem to make a difference.

_Originally posted by @R5fan in https://github.com/thanksmister/wallpanel-android/issues/212#issuecomment-821995167_

**Comment by thanksmister** [comment]
@R5fan you must provide your app version, saying you have the "latest" doesn't mean what you think because we have different versions depending on where you installed the app from, github, google, amazon.

**Comment by thanksmister** [comment]
Not reproducible in version https://github.com/thanksmister/wallpanel-android/releases/tag/v0.9.4.6

**Comment by squaredcircle** [comment]
I also have this issue on v0.9.4 build 2 from Google Play Store and on v0.9.4.6 installed manually from the .apk in the releases section. I'm using Lineage OS 18.1 (Android 11) on a Nexus 7 (2013). This tablet has a known issue where wifi sporadically disconnects and reconnects. This causes Home Assistant to show "Connection lost, reconnecting..." for about a minute before Wallpanel freezes, with Android asking me if I would like to wait or close the application. After some time eventually the app closes back to the home screen. I have had this happening over the last week and as such Wallpanel has been unusable. I'm happy to provide logs, etc if possible to help fix this issue.

**Comment by thanksmister** [comment]
@squaredcircle I don't have a way to test Lineage OS and reproduce the issue.  You are in uncharted territory without much support.  Maybe if you provide your device model I can check Firebase for crashes related to that device.   A couple of possible tests, try using a page that is not Lovelace, maybe its crashing the web site.  Try searching for an app that keeps your device connection active.

**Comment by squaredcircle** [comment]
@thanksmister I'm using a Nexus 7 (2013). I tried setting my page to the Australian News Corporation News 24 webpage playing the live video. When the tablet wifi went down, the video stopped. Soonafter the app crashed with "WallPanel isn't responding". Unfortunately I cannot use an app to keep my connection alive as this is a common unfixable issue with the tablet (https://issuetracker.google.com/issues/36958851). Is there anything else I can try?

**Comment by thanksmister** [comment]
I think a valid test would be using a webpage that is basic, either Tileboard for your Home Assistant page or just Google page. My theory is that the video is what is causing issues, which means the webpage is what is the cause of the crash or slowdown.  In Android, to display web pages, you are completely reliant on the WebView component, which is what renders pages, this component varies from system to system.  There are ways to update this to have better rendering, but I do not know if you can do that on your OS.

**Comment by squaredcircle** [comment]
![photo_2021-05-19_18-02-26](https://user-images.githubusercontent.com/7134818/118777626-9bb37280-b8cc-11eb-822e-aac82ca3548d.jpg)
Just tried with http://www.google.com, and saw the same issue after a few minutes when the tablet disconnected from wifi.

**Comment by thanksmister** [comment]
OK, I will do some more testing today to see if we can address this.

**Comment by adub08** [comment]
I can confirm the same issue on 2 different devices, 1 tablet and 1 phone, the app freezes on both upon wifi re-connection. Very reproducible. Both running 0.9.4.6. Both devices running different versions of Android i can provide more details if its any help.

**Comment by thanksmister** [comment]
I could not reproduce this issue with home assistant and network disconnect, both from the device and restarting the server.  What I have added is a way to detect network disconnect from the app and then refresh the web page when connected.  If HA restarts, I suggest adding a startup script to send refresh to the app from HA when the servers starts to refresh the websocket connection.    

If your app is freezing because the connectivity to the automation platform is disconnected, it's possibly the page itself causing a crash, I cannot detect this issue other than the entire app crashing.    I will continue to test connectivity issues to see if I can reproduce the same results.

**Comment by adub08** [comment]
I went through and tested it again, it doesn't seem to be dependent on loading home assistant as i could reproduce it with loading google.com as the web page. Same issue whether the wifi is being disconnected through android or the AP being unplugged, it crashes upon reconnection, not the actual disconnection. The 2 devices with the error are running Android 7.1.2 & 7.1.1.
I could not reproduce the issue on my main phone running android 10.

**Comment by thanksmister** [comment]
Ok I can test on Android 7 .

**Comment by thanksmister** [comment]
I released a new version that detects network connectivity issues and will reload the page if the network connects again.  I am not sure this will handle issues on Android 7 devices, but it was one issue reported by other users when the network is disconnected.    https://github.com/thanksmister/wallpanel-android/releases/tag/v0.9.4.9

**Comment by thanksmister** [comment]
Duplicate of https://github.com/thanksmister/wallpanel-android/issues/268

**Comment by thanksmister** [comment]
> I went through and tested it again, it doesn't seem to be dependent on loading home assistant as i could reproduce it with loading google.com as the web page. Same issue whether the wifi is being disconnected through android or the AP being unplugged, it crashes upon reconnection, not the actual disconnection. The 2 devices with the error are running Android 7.1.2 & 7.1.1.
> I could not reproduce the issue on my main phone running android 10.

Can you maybe try turning off hardware acceleration on your Android 7 devices.   There is a bug specific to this version of Android and the WebView component when using hardware acceleration.  This is just a guess, you may not have this on.

**Comment by thanksmister** [comment]
The other option is to update the WebView on those devices to see if we have some issue with rendering the page with the version you have on those devices.   WebView is a component found in Google Store and there are also versions you can download and install.

**Comment by adub08** [comment]
Thanks for the suggestion and for the fix.
I tested out 09.4.9 and it's only partially fixed unfortunately. The reloading the page works well, although unfortunately with Home assistant that means it will reload the home page ( not necessarily the page which was navigated to, i.e. different view ). It also seems to crash out of the app altogether if i leave it overnight. I'll look into how to update WebView on the tablet and try that out, thanks

**Comment by adub08** [comment]
Upgrading to webview 91.0.4472.77 (from 89.X) on the android 7.1 tablet unfortunately has not fixed the problem. Weirdly if I do the exact same test my android 10 phone running the same (latest) webview version, Wallpanel behaviors completely fine.

**Comment by thanksmister** [comment]
Did you try turning off/on hardware acceleration, this was a known bug on Android 7, it cannot have hardware acceleration on with webview.   I do not have a physical Android 7 device to test.

**Comment by adub08** [comment]
I did and same issue unfortunately. it seems to crash and reload the web page less though. it's also unusably slow unfortunately with a mildly complex home assistant page.

**Comment by adub08** [comment]
I have been able to resolve this on one of the two devices by flashing a custom android 9.0 ROM ( LineageOS 16), Although on the older Samsung Tab3 10.1, I don't believe i will be able to move to a newer version then 7.1.2.

**Comment by thanksmister** [comment]
I think we need to document for others the ongoing issues with Android 7 devices, possibly they cannot use the app on those devices.

**Comment by thanksmister** [comment]
New version with some fixes for keeping the device awake if the wake command is received. 
https://github.com/thanksmister/wallpanel-android/releases/tag/v0.9.5.1
